export const MONTHLY_SHEET_CATEGORIES = [
  { value: "NONE", label: "None" },
  { value: "RENT", label: "Rent" },
  { value: "STAFF_SALARY", label: "Staff salary" },
  { value: "INTERNET", label: "Internet" },
  { value: "ELECTRICITY", label: "Electricity" },
  { value: "WATER", label: "Water" },
  { value: "TRANSPORTATION_DELIVERY", label: "Transportation / delivery" },
  { value: "MARKETING_PROMOTION", label: "Marketing / promotion" },
  { value: "RAW_MATERIALS_INGREDIENTS", label: "Raw materials / ingredients" },
  { value: "PACKAGING", label: "Packaging" },
  { value: "LPG_COOKING_GAS", label: "LPG / cooking gas" },
  { value: "MAINTENANCE_REPAIRS", label: "Maintenance / repairs" },
  { value: "CLEANING_SUPPLIES", label: "Cleaning supplies" },
  { value: "POS_SOFTWARE_WALLET_CHARGES", label: "POS / software / wallet" },
  { value: "LICENSES_TAXES_MUNICIPALITY_FEES", label: "Licenses / taxes" },
  { value: "SECURITY_CCTV", label: "Security / CCTV" },
  { value: "STAFF_MEALS_TEA", label: "Staff meals / tea" },
  { value: "FESTIVAL_BONUS_OVERTIME", label: "Festival bonus / overtime" },
  { value: "BANK_CHARGES", label: "Bank charges" },
  { value: "MISCELLANEOUS", label: "Miscellaneous" },
] as const;
