import {
  Armchair,
  ArrowLeftRight,
  Calculator,
  ChartColumn,
  ChefHat,
  Coffee,
  HandCoins,
  Landmark,
  ScanLine,
  FileText,
  FolderTree,
  LayoutDashboard,
  LayoutGrid,
  Package,
  PackageMinus,
  ReceiptText,
  Settings,
  ShieldUser,
  ShoppingBag,
  ShoppingCart,
  Store,
  Tags,
  Truck,
  UserRoundSearch,
  Users,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Wheat,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  "receipt-text": ReceiptText,
  package: Package,
  armchair: Armchair,
  wrench: Wrench,
  "shopping-bag": ShoppingBag,
  "chart-column": ChartColumn,
  users: Users,
  settings: Settings,
  calculator: Calculator,
  store: Store,
  "shield-user": ShieldUser,
  "user-round-search": UserRoundSearch,
  "folder-tree": FolderTree,
  utensils: Utensils,
  "utensils-crossed": UtensilsCrossed,
  "chef-hat": ChefHat,
  wheat: Wheat,
  truck: Truck,
  "shopping-cart": ShoppingCart,
  tags: Tags,
  wallet: Wallet,
  "package-minus": PackageMinus,
  "hand-coins": HandCoins,
  "scan-line": ScanLine,
  "file-text": FileText,
  landmark: Landmark,
  "arrow-left-right": ArrowLeftRight,
};

export function getMenuIcon(icon?: string | null): LucideIcon {
  if (!icon) return Coffee;
  return ICON_MAP[icon] ?? Coffee;
}
